sudo: required
language: python
python:
  - '2.7'

env:
  - HEROKU_STACK=cedar-14

services:
  - docker

install: true
script: bash build.sh

deploy:
  provider: s3
  region: us-east-1
  access_key_id: AKIAI3U3FZ7PNMN5TRGA
  secret_access_key:
    secure: tYton3bTx8taneGKp+EmYsaCwSUqA8rr0GTMibj4WvYCC1yUziQyZT7pMfQK5iDSndTMAg85YV1guqmcL6wouKWrT72dvIl5i107vWFVCMiLEeDCtvPXxUJZ0Th8WqqaFtIcCeTIrFaRi4JcgzT85YryvOh/moCMkmmlb9pBydM=
  bucket: heroku-buildpack-elixir
  local-dir: builds/otp
  upload-dir: otp-builds
  acl: public_read
  on:
    repo: HashNuke/heroku-buildpack-elixir-otp-builds
    branch: master
